name: worms
channels:
 - schrodinger
 - conda-forge
 - https://conda.anaconda.org/t/IuO94WfD-JCG/rosettacommons
dependencies:
 - python >= 3.6
 - pyrosetta=2018.52
 - numpy=1.16.3
 - matplotlib
 - scipy
 - numba
 - pandas=0.24.2
 - xarray=0.11.3
 - pytest
 - pytest-faulthandler
 - sphinx_rtd_theme
 - ipython
 - cffi
 - pymol >= 2.1
 - python-blosc >= 1.5
 - pip
 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - tqdm
   - yapf
