name: worms
channels:
 - schrodinger
 - conda-forge
 - asford
dependencies:
 - python >= 3.6
 - pyrosetta
 - numpy
 - scipy
 - numba
 - xarray
 - pytest
 - pytest-faulthandler
 - sphinx_rtd_theme
 - ipython
 - cffi
 - pymol >= 2.1
 - python-blosc >= 1.5
 - pip:
   - homog >= 0.1.10
   - xbin >= 0.1.5
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - tqdm
   - yapf
