name: wormsnewnumba
channels:
 - schrodinger
 - conda-forge
 - https://pose:foldtree@conda.graylab.jhu.edu
dependencies:
 - python < 3.9
 - pyrosetta
 - numpy
 - matplotlib
 - scipy
 - numba
 - pandas
 - xarray
 - sphinx_rtd_theme
 - ipython
 - cffi
 - pymol >= 2.1
 - python-blosc >= 1.5
 - psutil
 - pympler
 - tqdm
 - yapf
 - pytest
 - pytest-faulthandler
 - pytest-xdist
 - pip
 - pip:
   - pytest-sugar

